name: C/C++ CI
on: [push, pull_request]
jobs:
  build-mac-default:
  # checking pure lib source distribution with plain configure & make
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make

  build-mac-default-full-bundle-1:
  # full bundle: enable all codecs + AEC + DTLS
  # full bundle 1: running pjlib, pjlib-util, pjmedia, and pjsua tests
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: brew install opencore-amr swig sipp
    - name: config site
      run: cd pjlib/include/pj && cp config_site_test.h config_site.h
    - name: configure
      run: CFLAGS="-g -I/usr/local/include -I/usr/local/opt/openssl/include -fPIC" LDFLAGS="-L/usr/local/lib -L/usr/local/opt/openssl/lib" CXXFLAGS="-g -fPIC" ./configure
    - name: make
      run: make
    - name: swig bindings
      run: cd pjsip-apps/src/swig && make
    - name: disable firewall
      run: sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
    - name: set up Python 2.7 for pjsua test
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: unit tests
      run: make pjlib-test pjmedia-test pjlib-util-test pjsua-test

  build-mac-default-full-bundle-2:
  # full bundle 2: running pjnath test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: brew install opencore-amr
    - name: config site
      run: cd pjlib/include/pj && cp config_site_test.h config_site.h
    - name: configure
      run: CFLAGS="-g -I/usr/local/include -I/usr/local/opt/openssl/include" LDFLAGS="-L/usr/local/lib -L/usr/local/opt/openssl/lib" ./configure
    - name: make
      run: make
    - name: disable firewall
      run: sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
    - name: unit tests
      run: make pjnath-test

  build-mac-default-full-bundle-3:
  # full bundle 3: running pjsip test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: brew install opencore-amr
    - name: config site
      run: cd pjlib/include/pj && cp config_site_test.h config_site.h
    - name: configure
      run: CFLAGS="-g -I/usr/local/include -I/usr/local/opt/openssl/include" LDFLAGS="-L/usr/local/lib -L/usr/local/opt/openssl/lib" ./configure
    - name: make
      run: make
    - name: disable firewall
      run: sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
    - name: unit tests
      run: make pjsip-test

  # build-ubuntu-no-tls:
  # no TLS (same as build-mac-default)

  build-mac-openssl:
  # TLS: with OpenSSL
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: brew install swig
    - name: configure
      run: CFLAGS="-I/usr/local/include -I/usr/local/opt/openssl/include -fPIC" LDFLAGS="-L/usr/local/lib -L/usr/local/opt/openssl/lib" CXXFLAGS="-fPIC" ./configure
    - name: make
      run: make
    - name: swig bindings
      run: cd pjsip-apps/src/swig && make

  build-mac-gnu-tls:
  # TLS: with GnuTLS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: brew install swig
    - name: configure
      run: CFLAGS="-fPIC" CXXFLAGS="-fPIC" ./configure --with-gnutls=/usr/local/
    - name: make
      run: make
    - name: swig bindings
      run: cd pjsip-apps/src/swig && make

  build-mac-video-openh264-1:
  # video: video enabled with vpx and openh264
  # video 1: running pjlib, pjlib-util, pjmedia, and pjsua tests
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: brew install openh264 libvpx opencore-amr swig sipp 
    - name: config site
      run: cd pjlib/include/pj && cp config_site_test.h config_site.h && echo "#define PJMEDIA_HAS_VIDEO 1" >> config_site.h
    - name: configure
      run: CFLAGS="-g -I/usr/local/include -I/usr/local/opt/openssl/include -DHAS_VID_CODEC_TEST=0 -fPIC" LDFLAGS="-L/usr/local/lib -L/usr/local/opt/openssl/lib" CXXFLAGS="-g -fPIC" ./configure
    - name: make
      run: make
    - name: swig bindings
      run: cd pjsip-apps/src/swig && make
    - name: disable firewall
      run: sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
    - name: set up Python 2.7 for pjsua test
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: unit tests
      run: make pjlib-test pjmedia-test pjlib-util-test pjsua-test
